name: deploy plugin

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'what kind of release is this?'
        type: choice
        required: true
        default: 'PATCH'
        options:
        - MAJOR
        - MINOR
        - PATCH
        - promote to stable
      open_pr:
        description: 'should a pr be opened for the deployment?'
        type: boolean
        required: false
        default: false

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: configure inputs
      id: configure-inputs
      env:
        RELEASE_TYPE: ${{ inputs.release_type }}
      run: |
        if [[ $RELEASE_TYPE == promote* ]]; then
          echo "version_change=NONE" >> $GITHUB_OUTPUT
          echo "deployment_type=stable" >> $GITHUB_OUTPUT
        else
          echo "version_change=$RELEASE_TYPE" >> $GITHUB_OUTPUT
          echo "deployment_type=testing" >> $GITHUB_OUTPUT
        fi
    outputs:
      version_change: ${{ steps.configure-inputs.outputs.version_change }}
      deployment_type: ${{ steps.configure-inputs.outputs.deployment_type }}

  deploy-plugin:
    uses: dit-zy/DalamudPluginDeploy/.github/workflows/deploy_plugin.yml@v1
    needs: prepare-deploy
    with:
      public_name: 'ScoutHelper'
      internal_name: 'ScoutHelper'
      project_dir: 'ScoutHelper'
      project_name: 'ScoutHelper'
      owners: 'dit-zy,zw3lf'
      version_change: ${{ needs.prepare-deploy.outputs.version_change }}
      deployment_type: ${{ needs.prepare-deploy.outputs.deployment_type }}
      github_username: 'dit-zy'
      github_email: 'dit.zy@pm.com'
      open_pr: ${{ inputs.open_pr }}
      force_push: true
    secrets:
      DEPLOY_TOKEN: ${{ secrets.PAT }}
